name: precious
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cart_stepper: ^4.3.0
  customizable_counter: ^1.0.4
  easy_image_viewer: ^1.4.1
  firebase_auth: ^4.19.0
  firebase_core: ^2.27.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.4
  google_auth: ^0.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: any
  modal_bottom_sheet: ^3.0.0
  shared_preferences: ^2.2.2
  sidebarx: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
