// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdX5ilWFYOCkh9YoDFyfOTl2ETqOcq1c',
    appId: '1:241842302669:web:8ffc3a5ff0d7797bcd8384',
    messagingSenderId: '241842302669',
    projectId: 'jewelry-store-uit',
    authDomain: 'jewelry-store-uit.firebaseapp.com',
    storageBucket: 'jewelry-store-uit.appspot.com',
    measurementId: 'G-J3BKZYMLX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3IKu-0BQpXXVtHocC6QaIWmi_qD2p-Fg',
    appId: '1:241842302669:android:bf119a970e8a5dc6cd8384',
    messagingSenderId: '241842302669',
    projectId: 'jewelry-store-uit',
    storageBucket: 'jewelry-store-uit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Onha20gs6CaGes77LtihYN-2TQWwkg4',
    appId: '1:241842302669:ios:5996432872825eb7cd8384',
    messagingSenderId: '241842302669',
    projectId: 'jewelry-store-uit',
    storageBucket: 'jewelry-store-uit.appspot.com',
    iosBundleId: 'com.example.precious',
  );
}
